import 'package:hive/hive.dart';

part 'todo.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0) // Annotate the class with HiveType and specify typeId
class Todo extends HiveObject {
  @HiveField(0) // Annotate each field with HiveField and specify index
  final String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String description;

  @HiveField(3)
  late bool isCompleted;

  // Provide a constructor without named parameters
  Todo({
    required this.id,
    required this.title,
    required this.description,
    required this.isCompleted,
  });

  Todo copyWith({
    String? id,
    String? title,
    String? description,
    bool? isCompleted,
  }) {
    return Todo(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }
}
